---
# Debian/Ubuntu specific variables for quantum-safe cryptography

# Package manager specific variables
package_manager: apt
update_cache: yes

# Debian/Ubuntu specific package names
system_packages:
  - build-essential
  - cmake
  - ninja-build
  - git
  - wget
  - curl
  - unzip
  - libssl-dev
  - python3-dev
  - python3-pip
  - python3-pytest
  - python3-pytest-xdist
  - python3-yaml
  - doxygen
  - graphviz
  - astyle
  - valgrind
  - pkg-config
  - autotools-dev
  - debhelper
  - dh-systemd

# Service management
service_manager: systemd
service_extension: ".service"

# Library paths
lib_path: "/usr/lib/x86_64-linux-gnu"
include_path: "/usr/include"

# Compiler settings
cc_compiler: "gcc"
cxx_compiler: "g++"
