---
- name: Delete the lock files
  file:
    dest: "{{ config_prefix|default('/') }}etc/wireguard/private_{{ item }}.lock"
    state: absent
  when: keys_clean_all|bool
  loop: "{{ users + [IP_subject_alt_name] }}"

- name: Generate private keys
  command: wg genkey
  register: wg_genkey
  args:
    creates: "{{ wireguard_pki_path }}/private/{{ item }}"
  loop: "{{ users + [IP_subject_alt_name] }}"

- block:
    - name: Ensure PKI directories exist before saving keys
      file:
        dest: "{{ item }}"
        state: directory
        recurse: true
      loop:
        - "{{ wireguard_pki_path }}/private"
        - "{{ wireguard_pki_path }}/preshared"
        - "{{ wireguard_pki_path }}/public"
      delegate_to: localhost
      become: false

    - name: Debug wg_genkey results
      debug:
        var: wg_genkey.results

    - name: Save private keys
      copy:
        dest: "{{ wireguard_pki_path }}/private/{{ item.item }}"
        content: "{{ item.stdout }}"
        mode: "0600"
      no_log: false
      when: item.changed | default(false) and item.stdout is defined
      loop: "{{ wg_genkey.results | default([]) }}"
      loop_control:
        label: "{{ item.item | default('undefined') }}"
      delegate_to: localhost
      become: false

    - name: Touch the lock file
      file:
        dest: "{{ config_prefix|default('/') }}etc/wireguard/private_{{ item }}.lock"
        state: touch
      loop: "{{ users + [IP_subject_alt_name] }}"
  when: wg_genkey.changed

- name: Delete the preshared lock files
  file:
    dest: "{{ config_prefix|default('/') }}etc/wireguard/preshared_{{ item }}.lock"
    state: absent
  when: keys_clean_all|bool
  loop: "{{ users + [IP_subject_alt_name] }}"

- name: Generate preshared keys
  command: wg genpsk
  register: wg_genpsk
  args:
    creates: "{{ wireguard_pki_path }}/preshared/{{ item }}"
  loop: "{{ users + [IP_subject_alt_name] }}"

- block:
    - name: Save preshared keys
      copy:
        dest: "{{ wireguard_pki_path }}/preshared/{{ item.item }}"
        content: "{{ item.stdout }}"
        mode: "0600"
      no_log: false
      when: item.changed | default(false) and item.stdout is defined
      loop: "{{ wg_genpsk.results | default([]) }}"
      loop_control:
        label: "{{ item.item | default('undefined') }}"
      delegate_to: localhost
      become: false

    - name: Touch the preshared lock file
      file:
        dest: "{{ config_prefix|default('/') }}etc/wireguard/preshared_{{ item }}.lock"
        state: touch
      loop: "{{ users + [IP_subject_alt_name] }}"
  when: wg_genpsk.changed

- name: Generate public keys
  shell: |
    set -o pipefail
    echo "{{ lookup('file', wireguard_pki_path + '/private/' + item) }}" |
    wg pubkey
  register: wg_pubkey
  changed_when: false
  args:
    executable: bash
  loop: "{{ users + [IP_subject_alt_name] }}"

- name: Save public keys
  copy:
    dest: "{{ wireguard_pki_path }}/public/{{ item.item }}"
    content: "{{ item.stdout }}"
    mode: "0600"
  no_log: false
  when: item.stdout is defined and item.item is defined
  loop: "{{ wg_pubkey.results | default([]) }}"
  loop_control:
    label: "{{ item.item | default('undefined') }}"
  delegate_to: localhost
  become: false
